-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 07:47:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vendadeproduto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vendadeproduto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendadeproduto` DEFAULT CHARACTER SET utf8 ;
USE `vendadeproduto` ;

-- -----------------------------------------------------
-- Table `vendadeproduto`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendadeproduto`.`categoria` (
  `idcategorias` INT NOT NULL,
  `dscartegoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendadeproduto`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendadeproduto`.`produto` (
  `idprodutos` INT NOT NULL,
  `dsprodutos` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `qtdade` INT NOT NULL,
  `foto` LONGBLOB NOT NULL,
  `categoria_idcategorias` INT NOT NULL,
  PRIMARY KEY (`idprodutos`),
  -- INDEX `fk_produto_categoria_idx` (`categoria_idcategorias` ASC) VISIBLE,
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`categoria_idcategorias`)
    REFERENCES `vendadeproduto`.`categoria` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendadeproduto`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendadeproduto`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendadeproduto`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendadeproduto`.`pedido` (
  `idpedido` INT NOT NULL,
  `data` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `sessao` VARCHAR(45) NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  -- INDEX `fk_pedido_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `vendadeproduto`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendadeproduto`.`pedidoitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendadeproduto`.`pedidoitem` (
  `idpedidoitens` INT NOT NULL,
  `qtade` INT NOT NULL,
  `preco` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `produto_idprodutos` INT NOT NULL,
  `pedido_idpedido` INT NOT NULL,
  PRIMARY KEY (`idpedidoitens`),
 -- INDEX `fk_pedidoitem_produto1_idx` (`produto_idprodutos` ASC) VISIBLE,
  -- INDEX `fk_pedidoitem_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedidoitem_produto1`
    FOREIGN KEY (`produto_idprodutos`)
    REFERENCES `vendadeproduto`.`produto` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidoitem_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `vendadeproduto`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
